### ISSUE TITLE
Update /privacy re: client ID

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/docs#119]

**Comment by eseidel** [comment]
We're presumably doing exactly what expo is re: MAUs and client_ids, so expo.dev/privacy should be a useful guide.

**Comment by bryanoltman** [comment]
It appears that this is already in our privacy policy:

> Collection of Information
> We collect the following categories of information when you use our Services (including when our mobile applications run on your device):
> ...
> **When end-users use apps made with Shorebird, we may collect anonymous device identifiers, if you are utilizing Shorebird’s code push service.**
