### ISSUE TITLE
Document how to use shorebird with fastlane

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/docs#233]
[fastlane](https://fastlane.tools/) is a popular way to automate iOS releasing. We should figure out how shorebird does (or doesn't) fit into this and document it.

**Comment by eseidel** [comment]
See also https://github.com/shorebirdtech/shorebird/issues/257

**Comment by bryanoltman** [comment]
It would probably be useful to create a [fastlane plugin](https://docs.fastlane.tools/plugins/create-plugin/) for shorebird
