### ISSUE TITLE
doc: Explain when to create a new release vs a patch

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/docs#236]
A customer had this question [here](https://discord.com/channels/1030243211995791380/1247923530981445633) and I don't think we currently provide guidance.

**Comment by tristdrum** [comment]
Great insight!

**Comment by bryanoltman** [comment]
Customer asked for this guidance in Discord https://discord.com/channels/1030243211995791380/1030243213002412164/1262435097966153808
