### ISSUE TITLE
docs: Add a guide on integrating Shorebird with Codemagic

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/docs#61]
We've had a few people ask.

Should be straightforward to do, similar to the github one:
https://docs.shorebird.dev/ci

I suspect someone in the community who happens to use both could write a great doc if we don't get to it first.

**Comment by nilsreichardt** [comment]
For all Codemagic users: the documentation on using Shorebird + Codemagic is live: https://docs.shorebird.dev/ci/codemagic

Please let me know if you would love to see more examples or if something should be clarified :v:
