### ISSUE TITLE
fix: mention that only release build variants are supported in add-to-app guide

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/docs#75]
It's not clear at the moment that shorebird in an add-to-app scenario only works with the `release` build variant. This should be called out/made more prominent.

![image](https://github.com/shorebirdtech/docs/assets/581764/ad93f5aa-baab-499b-b70f-204101d8f5ea)

**Comment by eseidel** [comment]
This is done. https://docs.shorebird.dev/guides/code_push_add_to_app
