### ISSUE TITLE
Document the flow for creating both iOS and Android from same machine.

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/docs#87]
We'll probably want to update this on:

1. [x] https://docs.shorebird.dev/code_push/release
2. [x] https://docs.shorebird.dev/code_push/patch
3. [x] https://docs.shorebird.dev/guides/code_push_quickstart
4. [x] https://docs.shorebird.dev/code_push/preview depending on where that work lands
5. [x] https://docs.shorebird.dev/guides/code_push_release
6. [ ] https://docs.shorebird.dev/architecture if @eseidel wants to talk about our Dart sdk modifications
7. [x] Update `shorebird release ios-preview` warning text.

**Comment by bryanoltman** [comment]
I believe this is simply:

1. `shorebird init`
2. `shorebird release android`
3. `shorebird release ios-preview`
4. (Dart changes)
5. `shorebird patch android`
6. `shorebird patch ios-preview`

**Comment by bryanoltman** [comment]
We'll probably want to update this on:

1. https://docs.shorebird.dev/code_push/release
2. https://docs.shorebird.dev/code_push/patch
3. https://docs.shorebird.dev/guides/code_push_quickstart
4. https://docs.shorebird.dev/code_push/preview depending on where that work lands
5. https://docs.shorebird.dev/guides/code_push_release (probably less urgent than the others)
6. https://docs.shorebird.dev/status to move iOS from a "coming soon" to a "usable but not production-ready" preview state.
7. https://docs.shorebird.dev/faq#what-platforms-does-shorebird-support-does-it-support-ios same as above
8. https://docs.shorebird.dev/architecture if @eseidel wants to talk about our Dart sdk modifications

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/docs/pull/52
